### ISSUE TITLE
32 bit Issues

### ISSUE THREAD

**Issue by aviks** [quinnj/Datetime.jl#20]
``` jlcon
julia> versioninfo()

Julia Version 0.2.0-rc2
Commit b372a68 2013-10-26 02:06:56 UTC
Platform Info:
  System: Windows (i686-w64-mingw32)
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

julia> using Datetime

julia> isdefined(:Datetime)
true

julia> date(2103,10,27)
2103-10-27

julia> datetime(2103,10,27,11,10,9)
ERROR: no method datetime(Int64,Int64,Int64,Int64,Int64,Int64,DataType,DataType)
```

Similar code works well on a 64 bit install

``` jlcon
julia> versioninfo()
Julia Version 0.2.0-rc1-prerelease+4163
Commit as/pkgfix/5259264* 2013-10-22 10:33:18 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin11.4.2)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

julia> datetime(2013,10,27,11,10,9)
2013-10-27T11:10:09 UTC
```

**Comment by aviks** [comment]
Fix in #21

**Comment by quinnj** [comment]
Yeah, I thought the new fallback constructor was not quite right. This actually brings up another thought I had recently. I've been wondering if we should move the timezone and calendar arguments to named arguments. At least the calendar argument. I think it makes more sense that way. Not sure about the timezone though as it's nice to write:

``` julia
datetime(2013,10,27,0,0,0,EST)
```

As an FYI, the new problems here are because of adding the millisecond portion to the constructor.

**Comment by aviks** [comment]
> As an FYI, the new problems here are because of adding the millisecond portion to the constructor.

Yeah, I figured as much.

**Comment by aviks** [comment]
On TZ and Calendar being named arguments, yeah, I'm conflicted. Probably leave it as is and see how people feel after using it a bit.
