### ISSUE TITLE
abstract AbstractTime <: Real

### ISSUE THREAD

**Issue by gitfoxi** [quinnj/Datetime.jl#27]
Here's a weird idea: Datetime types have something -- maybe everything -- in common with Real numbers.

I was thinking about generic programming and how things that are like real numbers could inherit a lot of functionality. Specifically I was thinking about a histogram of a collection of `Date{ISOCalendar}` but it probably applies to lots of types, `Datetime` and otherwise.

If I change a line at the top of `Datetime.jl` to:

```
abstract AbstractTime <: Real
```

and provide a more generic `histrange{T <: Real}` (the implementation in `statisitcs.jl` is specialized for `<: Integer` and `<: FloatingPoint` but it can be dealt with) and I ignore 100 warnings when `using Datetime` then I can do this:

``` jl
using Datetime
d=today()
ds=[d,d,d+day(2),d+day(1),d+day(10)]
drange = histrange2(ds,5)
for hd in histrange2(ds,5)
    @show hd
end
@show drange
```

and get something semi-intelligible:

```
hd => 2013-12-25
hd => 2013-12-27
hd => 2013-12-29
hd => 2013-12-31
hd => 2014-01-02
hd => 2014-01-04
hd => 2014-01-06
drange => 2013-12-25:0001-01-02:2014-01-06
```

It makes me wonder about the possibilities.

**Comment by gitfoxi** [comment]
I looked into it some more and read your documentation and, yeah, clearly there's some other priorities taking precedence over easily inheriting Real-number functionality.

Some things I would like to see work:
- Histograms (`statistics.jl`)
- Regression.jl
- Loess.jl
- Any statistical transformations supported by Gadfly.jl or added in the future

The main thing is that you want to convert `Date` and `DateTime` to `Float64` for use inside the models and predictors but then convert them back to `Date` or `DateTime` when you return the prediction.

``` jl
julia> date(float64(today()))
735229-01-01
```

Doesn't quite work, but you can see how it might be made to.

``` jl
julia> datetime(float64(now()))
ERROR: no method datetime(Int64, Int64, Int64, Int64, Int64, Int64, Type{Zone0}, Type{ISOCalendar})
 in datetime at /Users/m/.julia/Datetime/src/Datetime.jl:142 (repeats 2 times)
```

Is worse but there's hope. Also, `Date` and `DateTime` aren't at the right place in the type hierarchy so that they get automatically promoted and that's probably the hard part to address.

I hoped (but now, I don't think) there's a magic 1-liner which can give `DateTime`s the power of real numbers. Especially in the case of plots where you might want to summarize or subdivide by Months or Weeks or Quarters (does DateTime have Quarters? -- seems no). It might even be easier to implement special wrappers in the other projects than to fix it in Datetime.jl. I guess I won't know until I try. I wonder what @dcjones thinks.

**Comment by quinnj** [comment]
So I couldn't quite grasp what you're looking for, but I would think we should be able to accommodate. I'm actually in the middle of doing a fairly heavy rewrite, most notably changing the Date/Datetime/Period types to immutables with single fields to represent their numerical values as Int64s. At that point, it's just a matter of carefully defining the arithmetic operations (+, -, *, div, mod) and perhaps some promotions as well. If you know which operations specifically seem to be missing, I'd love to hear so we can figure out the best operations/promotions to put in place.

**Comment by gitfoxi** [comment]
Cool. I'm glad I didn't monkey with it too much while you're in the middle of a big rewrite.

Simple example: I have a table of Date, GDP. I can make a plot of GDP/Date or Date/GDP but now I want a model such as a `gdp(date) = a*date + b` where I ask the Regression package to find `a` and `b` for me. Problem: Regression's functions type-assert that inputs must be `<: FloatingPoint`. All that's required to use it (with a little massaging) is for:

```
d = today()
@test date(float64(d)) == d
```

And also for the conversion to be linear so for any `Float64 x`:

```
@test date(x + float64(d)) == d + days(x)
@test date(x*float64(d)) == d*days(x)
```

As long as you can do that, the scale is linear. You don't need operators or anything. It might be harder to satisfy the same criteria for `DateTime` what with the leap seconds and time zones and such. Also, even 'Date' might have a hard time with leap years. I don't know. Probably. It would be nice if there were some way to accomplish it, at least within a given time zone or epoch.

After that, the only problem is the user must still call a conversion on his way into and out of the model. You have to say

```
m = model(gdp, float64(dates))
p = date(predict(14e12))  # predict the date GDP will hit 14-trillion
```

You'd prefer to call it like this and have it just work:

```
m = model(gdp,dates)
p = predict(14e12)
```

The first line requires that `Date` can be automatically promoted to `Float64` which I think can be automatic. But to achieve both simplifications, the `Regression.jl` (or whatever function provides the model/predict) would have to allow more abstract input, such as `<: Real` and it would have to take responsibility for recording the original type of the input and converting the output back to that type. Even though it's on `Regression.jl` to do that, and it could special-case `Date` and `DateTime`, I think it would be better if there was some abstraction in the type hierarchy, such as `Real` where any scale under that is acceptable with the only requirement being it linearly converts to and from `Float64`.

If you're using `Int64` then conversion to `Float64` will loose precision unless you can limit it to 52-bits.

**Comment by quinnj** [comment]
Thanks for the detailed comment; that helps a lot in understanding the situation. This actually touches a few different issues that, IMO, span a few different packages.

It sounds to me that what you're really looking for with the model/predict part is a TimeSeries/DataSeries type (I forget which one does what), which @milktrader has put in packages. Though I haven't used them extensively yet, the idea is that you have a Series type that holds both a column of Date/DateTimes as well as column of an Index which is a map of the dates to Int64 or Float64. When performing operations, methods are defined to either look at the Date side or the Index side for whichever is needed. (Note this could be way off, perhaps @milktrader can help clarify).

At that point, I think what we'd need is for the TimeSeries/DataSeries packages to define a dependency on Distributions and provide they're own methods for the Series types. 

If use of the Series type is way off, then the next solution would be to work with @dahua in defining the appropriate methods on the Date/DateTime types. That part is pretty easy and then converting back to Date types shouldn't be too difficult with the new rewrite (currently it takes a bit more work). The only tricky part in how the new Date/DateTime types will work is that you have to specify the type parameters explicitly, so:

``` julia
a = Date(2013,1,1)
b = a.days #access the numerical value of the Date as an Int64
c = Date{Millisecond,UTC,ISOCalendar}(b)
@assert a == c
```

**Comment by gitfoxi** [comment]
I will definitely checkout `TimeSeries.jl`. Above, I referred to `Distributions.jl` when I should have been saying `Regression.jl` and `Loess.jl`.

**Comment by dcjones** [comment]
This is a general issue I struggled with this in Gadfly, not really specific to Datetime. Some types are able to be plotted and others not, but there is no abstract type in the hierarchy that captures that. In the end, I just used `Any` all over the place, so it's essentially duck-typed.

I think there is a lot of other code (e.g. histogram, loess, regression) that has the same issue: it should be written more generically than it is, but it's not clear how other than duck typing. Duck typing works, but you lose clarity that type annotations add to an API, not to mention the confusing error messages when things go wrong.

So I agree that this is an issue. I don't think making types convertible to `Float64` is a great solution. I don't know what the number I get from `float64(today())` means. Short of making changes to Julia, the real solution is to figure out the right abstraction, amend the type hierarchy, and fix all the non-generic code.

**Comment by StefanKarpinski** [comment]
This is a bit of a strange place to bring it up, but I think we really need something like an interface or protocol – essentially a reification of abstractions that are currently identified at most by an abstract type or just by duck typing. These are the "narrow waists", above which one writes generic code to the abstraction, and below which one writes an implementation. You can mix and match the thing above and the thing below. We have these all over the place. The iterable abstraction is a wildly successful one – supply start, next and done methods and presto! you've got a thing that we can iterate over efficiently. The search interface for strings is another one: you implement search for some kind of string and pattern and you immediately get split, rsplit, replace, etc. for free because those things are all written generically in terms of search. The sorting API is another great one. You have all these different sorting functions with sophisticated implementations and options and then you've got various sorting algorithms – and they're completely mix-and-match. You can write and plug in a new algorithm and it just works with everything.

But those are the good clean cases. Then there's strings, which are much less well-defined. The abstraction is some kind of thing that yields a sequence of characters. But what is the interface exactly? Worse still are arrays and array-like things. The fact that any package that tries to extend the AbstractArray class ends up in an intractable mess of ambiguity warnings is a very bad warning sign. Something is horribly wrong here. Sure, we could clarify this particular interface, clean up the code, get rid of the warnings and document it well. We should do all of those things. But this is just going to keep happening. I think that the root of the problem is that the single most important thing in Julia – the interface, the abstraction, the protocol – is not an actual thing. There is no there there – it's just vaguely implied. We need to figure out how to reify this crucial thing. You should _declare_ in _code_ what the abstraction is. And an abstraction has two sides: what it requires from an implementor and what it provides to the user. I think those should be separated. A huge part of the reason we're seeing so many ambiguity warnings is that these are all thrown in together. Usually the implementor-facing side is simple and fairly rigid, with a handful of generic functions and a simple, fixed signatures to be implemented. The user-facing side, on the other hand, is full of messy convenience methods with variable numbers of arguments, default values and keyword arguments. It's the user-facing side that's causing all the ambiguity warnings, but all the package writer wants to do is plug into the clean, simple implementor-facing side.

A huge difficulty here is that a single type will need to be able to implement and inherit generic behavior from multiple abstractions, and that means something like mixins or multiple inheritance needs to exist. But the whole power of Julia's multiple dispatch system comes from the fact that abstractions are extensible, so we'd need the ability to inherit from multiple abstractions, yet allow each abstraction to be extended – at least on the user-facing side where people write new generic methods in terms of an abstraction.

**Comment by gitfoxi** [comment]
@StefanKarpinski That's a lot to think about. I will think some more and maybe put an RFC on JuliaLang.

I'm not going to be the one who figures out Julia's answer to mixins or multiple-inheritance but following the pattern of **iterable** there's room for **linearizable**. Something like, you just have to implement `linearize(BT::BitsType, v::YourType)` and `convert{BT <: BitsType}(::Type{YourType}, lv::Linearized{BT}` for your `DateTime`, `Decibel{:MilliWatts}` or whatever and then lots of things like histograms, plotting, sorting, various statistical models, transforms and just basic `+ - / * ^` operators can magically work for you.

I will have to do some more thinking and experiments to figure out how or if this might work with `Complex` numbers, `Range`s and higher dimensions, but I have a good feeling.

**Comment by milktrader** [comment]
To clarify where TimeSeries, DataSeries and Series fits in. 

TimeSeries is an unfortunate name for a package that provides tools for dealing with serialized data in the DataFrames/DataArrays data structure. I've put out an RFC to change the name of the package to DataSeries here: https://github.com/JuliaLang/METADATA.jl/issues/472

To add to the confusion, I also announced on google groups that I'm starting work on a package to work with serialized data called DataSeries.jl. That package name has been changed to Series.jl. https://github.com/milktrader/Series.jl/issues/16

My current thought is that TimeSeries be renamed DataSeries. Tools for working with serialized data in the DataFrames/DataArrays framework. It's more general than TimeSeries, and suggests affiliation with DataFrames/DataArrays.

Series, which I've been adding methods to during the past few days, is still un-registered and as yet an unformed idea. The Series type is `SeriesPair{T,V}`. Interestingly, by creating an array of this type, many of the array methods are made available (some need a small bit of code such as `sort`). So far, I've got it almost running (like a jalopy in a garage) and plan to build some models with it in the JuliaQuant organization.

**Comment by milktrader** [comment]
btw, here is the definition of SeriesPair to provide context:

``` julia
immutable SeriesPair{T, V} <: AbstractSeriesPair
  index::T
  value::V
  name::String
end
```

And to construct an array of this type, the SeriesArray method

``` julia
function SeriesArray{T,V}(idx::Array{T,1}, val::Array{V,1}, nm::String)
  res = SeriesPair{T,V}[]
  for i = 1:size(idx,1)
    x = SeriesPair(idx[i], val[i], nm)
    push!(res, x)
  end
  res
end
```

**Comment by quinnj** [comment]
I really liked @StefanKarpinski's point on interfaces. I definitely think some additional language support is needed here. There's been several moments where I wasn't quite sure which methods to implement in order to get iteration working or my own Range{T} type. I wonder if we want to go the formal interface route, something along the lines of:

``` julia
# Declare an interface and methods + signatures to implement
interface Iterable
    start(iter)
    next(iter, state)
    done(iter, state)
end

# Implement an interface
implement DatetimeRange <: Iterable
    start(r::DatetimeRange) = 0
    next(r::DatetimeRange, i) = (r.start + i*r.step, i+1)
    done(r::DatetimeRange, i) = (length(r) <= i)
end

# Abstract types can "inherit" 0 or more interfaces
abstract Ranges{T} <: AbstractArray{T,1}, Iterable
```

Just a little thought exercise I was going through last night to see what something like interfaces would look like in Julia. I'm not quite sure I fully grok why the separation of implementor-facing vs. user-facing is so important though.

**Comment by StefanKarpinski** [comment]
> I'm not quite sure I fully grok why the separation of implementor-facing vs. user-facing is so important though.

This is new ground so I'm not entirely sure that it is – and indeed, we have been getting by without separating these. However, I suspect that the scourge of ambiguous methods that we keep seeing in packages implementing array-like behaviors stems from this lack of separation. Someone comes along and wants to implement something that acts a lot like a matrix – say a data frame. They write some methods that are meant to implement basic operations on them, but they end up conflicting with all the fancy convenience methods that are written generically for matrix-like things. If the "method spaces" for the implementation and the generic code written to the interface were separate, then they couldn't conflict. When I was writing all the sorting API stuff making the implementation side – the method that you define to implement a new sorting algorithm – I was considering giving it a different name like `_sort!`. That's because the `sort!(v::AbstractVector, lo::Int, hi::Int, a::Algorithm, o::Ordering)` methods aren't really meant to be called directly – you should use `sort!(v,by=f)` and such.
