### ISSUE TITLE
Made a Julian date conversion

### ISSUE THREAD

**Issue by jsbj** [quinnj/Datetime.jl#29]
Hey there karbarcca, I wanted a Julian Date conversion, e.g.

```
# Julian conversion
Base.Test.@test datetime(2452695.625) == datetime(2003, 2, 25, 3)
Base.Test.@test datetime(2456630.375) == datetime(2013, 12, 3, 21)
```

so I made one; pull request forthcoming. The code is not as golfy as it could be; it was mostly ganked from some javascript...

**Comment by StefanKarpinski** [comment]
If you derived the code from somewhere else please be careful about the license. We need to make sure that code that we can't legally use does not get mixed into our legal code.

**Comment by jsbj** [comment]
OK – I'll go find a source with a more explicit license, or alternately, derive it from the actual conversions needed. Also, sorry about the double issue/pull request; new to OSS, clearly...

**Comment by StefanKarpinski** [comment]
No worries – thanks for taking this on, it's much appreciated. If the original source is MIT-compatible, we could use it. Or if you write it yourself and can relicense it at will, that's ok too.

**Comment by jsbj** [comment]
OK, reforked and wrote something from scratch. Didn't realize the implications of the "proleptic Gregorian" idea, so it was much simpler than I realized, or at least that's my understanding. New pull request!

**Comment by quinnj** [comment]
Hey @jsbj, really sorry to be so slow in following up here, but I'm actually in the process of migrating this package into Base julia. I'm following up now on all these issues to make sure they get resolved and put into base if needed.

Can you help me understand where the "julian" float numbers are coming from? Is this how javascript internally represents times/datetimes? Is this a standard thing in other languages? How is this different that Unix time, which represents the number of seconds since 1970-01-01T00:00:00 UTC. That should help clarify if there's overlap or not. We already have `ratadays2date/date2ratadays` and `unix2date/date2unix`, so we can easily add `julian2date/date2julian`.

**Comment by jsbj** [comment]
Hi @karbarcca, Julian date is different than Unix time (e.g., http://aa.usno.navy.mil/data/docs/JulianDate.php). It's similar, except the epoch was some date that various folks used to think was the creation of the world. It comes up surprisingly often in weather/climate data – I wrote the parser when I was looking at NASA satellite data of the solar constant, and all the datetime fields were in Julian dates.

**Comment by quinnj** [comment]
Ah, it's all coming back to me now. Back when I implemented the original date algorithms for this package, the other form of the algorithms was given in Julian days, I totally forgot. (http://mysite.verizon.net/aesir_research/date/date0.htm). Yeah, this would definitely be useful then and it's pretty easy to implement. I'll port your code to the Base PR.

**Comment by quinnj** [comment]
This is available in the new `dev` branch.
