### ISSUE TITLE
Default date string parsing tries to be too clever

### ISSUE THREAD

**Issue by jiahao** [quinnj/Datetime.jl#35]
A series of dates in `MM/dd/yyyy` format is inconsistently parsed without throwing errors

``` julia
julia> date("18/05/2009")
2009-05-18

julia> date("08/05/2009")
2009-08-05
```

The date constructor apparently looks for `dd/MM/yyyy`, which silently falls back to `MM/dd/yyyy`. This is quite a gotcha when parsing an array of dates in a consistent string format and this behavior of `date`'s default string parsing could at the very least be documented better.

[jiahao: changed mm to MM for months instead of minutes]

**Comment by quinnj** [comment]
Yeah, I always had the sinking feeling that default parsing was a bit of landmine; even more so because it's not documented anywhere. There's actually new machinery for parsing in the [Base PR](https://github.com/JuliaLang/julia/pull/5328) which should be a bit more sensible. I'll make sure we're adding some tests/documentation around this.

**Comment by quinnj** [comment]
Ok, I've tweaked this so that we only default parse according to how Date/DateTime are formatted.

``` julia
const ISODatetimeFormat = DatetimeFormat("yyyy-mm-ddTHH:MM:SS zzz","T")
const ISODateFormat = DateFormat("yyyy-mm-dd")
```

So no more surprises here.

**Comment by quinnj** [comment]
Should be fixed by newest `dev` branch. ed8123ede2e316a181a781ecd54fd735657b6cd8
