### ISSUE TITLE
Time-ago functionality

### ISSUE THREAD

**Issue by IainNZ** [quinnj/Datetime.jl#56]
I'm thinking of porting https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js to Julia - should it live in Datetime or a separate package?

**Comment by quinnj** [comment]
Good question. So once 0.3 is tagged, Stefan and I are going to try to figure out how to merge https://github.com/quinnj/Dates.jl into Base (either by submodule, or porting hte code in directly), and because we want to keep Base slim, I've been hand-picking things to go into a future "DateExtensions" package. Seems like that would be a good fit for some extra functionality like this. In the mean time, if you want to make a PR or describe how this works at https://github.com/quinnj/Dates.jl, I'd be happy to take a look and help out + merge code over there.

**Comment by quinnj** [comment]
Hey @IainNZ, I've created the [DateExtensions.jl[(https://github.com/quinnj/DateExtensions.jl) (still unregistered) to play with more exotic features and experiment with things. Feel free to make a PR there if you're interested.

**Comment by IainNZ** [comment]
I ended up making it!
https://github.com/IainNZ/Humanize.jl

**Comment by quinnj** [comment]
Cool! Looks great!
