### ISSUE TITLE
Package does not load under linux, case sensitivity issue.

### ISSUE THREAD

**Issue by haltux** [quinnj/Datetime.jl#6]
The package name is Datetime, but the module is declared in a file called datetime.jl
Renaming datetime.jl to Datetime.jl solves the problem.

**Comment by quinnj** [comment]
Good point. I was following the trend of Base in naming the file all lowercase, but that doesn't work well with packages because the name of the file is tied to `using module` behavior. I actually fixed this in [Datetime2](https://github.com/karbarcca/Datetime2.jl) (which is Date/DateTime support without timezone/leap second functionality) after your suggestion. This repo will be renamed at some point to DateExtensions, so I'll keep this open until the change happens.

**Comment by quinnj** [comment]
Closed by 28e8dbc
